/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/album/index.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    Image: typeof import('./src/components/image.vue')['default']
    Level: typeof import('./src/components/level.vue')['default']
    Like: typeof import('./src/components/like/index.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MyPlay: typeof import('./src/components/MyPlay/index.vue')['default']
    MyVideo: typeof import('./src/components/MyVideo/index.vue')['default']
    PlayVideo: typeof import('./src/components/playVideo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Song: typeof import('./src/components/song.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Svg: typeof import('./src/components/svg/index.vue')['default']
  }
}
